#Duration formatting examples: 1h, 2d, 3m, 4y, -1
Reasons:
  Mute:
    1:
      Name: "Insult"
      Duration: "1d"
    2:
      Name: "Spamming"
      Duration: "1h"
  Ban:
    1:
      Name: "Hacking"
      Duration: "-1"
    2:
      Name: "Trolling"
      Duration: "1m"